### ISSUE TITLE
Error while running webthing-tester

### ISSUE THREAD

**Issue by maliknaik16** [mozilla-iot/webthing-tester#3]
I'm getting the following error while trying to run webthing-tester:

```bash
$ python test-client.py
Traceback (most recent call last):
  File "test-client.py", line 562, in <module>
    exit(run_client())
  File "test-client.py", line 113, in run_client
    code, body = http_request('GET', '/')
  File "test-client.py", line 87, in http_request
    response = client.fetch(request, raise_error=False)
  File "C:\Python\lib\site-packages\tornado\httpclient.py", line 132, in fetch
    response = self._io_loop.run_sync(
  File "C:\Python\lib\site-packages\tornado\ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "C:\Python\lib\site-packages\tornado\simple_httpclient.py", line 330, in                                                                                                     run
    stream = await self.tcp_client.connect(
  File "C:\Python\lib\site-packages\tornado\tcpclient.py", line 280, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
  File "C:\Python\lib\site-packages\tornado\tcpclient.py", line 110, in start
    self.try_connect(iter(self.primary_addrs))
  File "C:\Python\lib\site-packages\tornado\tcpclient.py", line 128, in try_conn                                                                                                    ect
    stream, future = self.connect(af, addr)
  File "C:\Python\lib\site-packages\tornado\tcpclient.py", line 334, in _create_                                                                                                    stream
    return stream, stream.connect(addr)
  File "C:\Python\lib\site-packages\tornado\iostream.py", line 1219, in connect
    self._add_io_state(self.io_loop.WRITE)
  File "C:\Python\lib\site-packages\tornado\iostream.py", line 1050, in _add_io_                                                                                                    state
    self.io_loop.add_handler(self.fileno(), self._handle_events, self._state)
  File "C:\Python\lib\site-packages\tornado\platform\asyncio.py", line 102, in a                                                                                                    dd_handler
    self.asyncio_loop.add_writer(fd, self._handle_events, fd, IOLoop.WRITE)
  File "C:\Python\lib\asyncio\events.py", line 507, in add_writer
    raise NotImplementedError
NotImplementedError
```
**Python version**
3.8.1

**Python package list**
```
Package          Version
---------------- -------
attrs            19.3.0
ifaddr           0.1.6
jsonschema       3.2.0
pip              19.3.1
pyee             6.0.0
pyrsistent       0.15.7
setuptools       41.2.0
six              1.13.0
tornado          6.0
websocket-client 0.57.0
webthing         0.12.0
zeroconf         0.24.4

```

What is the right way to run the webthing tester?

**Comment by mrstegeman** [comment]
You ran it right, but I've never used it on Windows, so maybe that's the issue?

By the way, this is not a generic test script. It was written to test specific examples from our various webthing-X libraries.

**Comment by maliknaik16** [comment]
@mrstegeman Thanks for the reply.

I've implemented the webthing library in PHP and I was testing it.

Web Thing PHP: [https://github.com/maliknaik16/webthing-php](https://github.com/maliknaik16/webthing-php)

**Comment by mrstegeman** [comment]
Oh, cool! The test script here should be used to test the "Single Thing" example, or the lamp device of the "Multiple Things" example.

If you have Docker available, you should be able to get this script running really easily in a python:3.7 Docker container.

**Comment by maliknaik16** [comment]
Ok, then I'll try to run this script using docker.

Thanks.

**Comment by maliknaik16** [comment]
I've tried to run this script on Linux Mint with Python 3.7 but I got the following error:

```bash
Traceback (most recent call last):
  File "test-client.py", line 562, in <module>
    exit(run_client())
  File "test-client.py", line 113, in run_client
    code, body = http_request('GET', '/')
  File "test-client.py", line 87, in http_request
    response = client.fetch(request, raise_error=False)
  File "/usr/local/lib/python3.7/dist-packages/tornado/httpclient.py", line 133, in fetch
    functools.partial(self._async_client.fetch, request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
ConnectionRefusedError: [Errno 111] Connection refused
```
**Operating System:** Linux Mint 18.3 Cinnamon 
**Cinnamon version:** 3.6.7

**Comment by mrstegeman** [comment]
Seems like you can't route to your web thing. There are some command line arguments you can use. Run `./test-client.py -h` to see.

In particular, you'll probably need to use `--host` and `--port`.

**Comment by maliknaik16** [comment]
@mrstegeman Thanks for the reply.

Now I'm able to run the script on Linux.

**Comment by mrstegeman** [comment]
Great!

By the way, are you interested in having your library added to the bottom of [this page](https://iot.mozilla.org/framework/)?

**Comment by maliknaik16** [comment]
Yeah! I'm interested in having my library added there.

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/mozilla-iot.github.io/pull/70

**Comment by maliknaik16** [comment]
Thanks for opening an issue.
